apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-services
  template:
    metadata:
      labels:
        app: business-services
    spec:
      containers:
        - name: business-servicesapp
          image: 7720001490/myrepo:billingservices
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: business-services
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: business-services
