apiVersion: apps/v1
kind: Deployment
metadata:
  name: municipal-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: municipal-services
  template:
    metadata:
      labels:
        app: municipal-services
    spec:
      containers:
        - name: municipal-servicesapp
          image: 7720001490/myrepo:bpaservices
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: municipal-services
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: municipal-services
