apiVersion: apps/v1
kind: Deployment
metadata:
  name: microui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microui
  template:
    metadata:
      labels:
        app: microui
    spec:
      containers:
        - name: c1
          image: 7720001490/myrepo:microui
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: microui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: microui
